#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
#$HOME/.config/polybar/launch.sh
bash ~/.config/polybar/launch.sh --shapes
bash ~/.config/polybar/shapes/scripts/colors-dark.sh --gray
feh --bg-fill $HOME/Pictures/ledu-jan1.jpg
compton &
# redshift &
# bspwm-focused-top &

bspc monitor -d I II III IV V VI VII VIII IX X

###--- Global settings ---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
#bspc config pointer_modifier shift
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
bspc config click_to_focus button1

bspc config focus_follows_pointer false

bspc config normal_border_color "#000000"
bspc config active_border_color "#511331"
bspc config focused_border_color "#FFFFFF"

###--- Monitor & Desktop settings ---###
bspc config border_width    2
bspc config window_gap      2
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config top_padding     34

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Minesweeper state=floating
bspc rule -a Gnome-terminal state=floating
# bspc rule -a Alacritty state=floating
# bspc rule -a Vivado state=floating
bspc rule -a Java state=floating
bspc rule -a Nemo state=floating
bspc rule -a Thunar state=floating
bspc rule -a Putty state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a qBittorrent desktop='^4' state=floating follow=on
bspc rule -a Deadbeef desktop='^3' state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
