#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/ledu-jan1.jpg
picom &
redshift &

bspc monitor -d I II III IV V VI VII VIII IX X

###--- Global settings ---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
#bspc config pointer_modifier shift
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true

bspc config normal_border_color "#7f1e55"
bspc config active_border_color "#511331"
bspc config focused_border_color "#ff99cc"

###--- Monitor & Desktop settings ---###
bspc config border_width    3    
bspc config window_gap      3 
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config top_padding     36 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pamac-manager state=floating
bspc rule -a qBittorrent desktop='^4' state=floating follow=on
bspc rule -a Nautilus desktop='^4' state=floating follow=on
bspc rule -a Deadbeef desktop='^3' state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
